Добавил контроллеры и модели
ArigatoSlayer/java-filmorate pull request #4
Opened 2023-10-29 22:45 UTC by ArigatoSlayer

2023-11-01 00:50 UTC, ArigatoSlayer commented
Задание прошло все проверки

2023-11-01 20:37 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе

2023-11-01 20:37 UTC, Frilock commented on pom.xml
> +			<version>3.0.2</version>
Версии библиотек, которые вы подключаете в pom файле, правильнее писать в preporties (по аналогии с версией java), поскольку pom файлы могут быть очень большого размера и изменение версии библиотеки может оказаться не такой простой задачей.

2023-11-01 20:37 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    //    @Past(message = "Дата рождение написано в будущем времени")
Закоментированный код не нужно оставлять в приложении

2023-11-01 20:37 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean isValidFilm(Film film) {
А зачем использовать и свою кастомную валидацию и валидацию спринга? Не проще ли еще добавить пару аннотаций на классы фильма и юзера?

2023-11-01 20:37 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films")
Когда все публичные методы контроллера имеют один префикс в маппинге, то можно на контроллер повесить аннотацию RequestMapping и там указать его

2023-11-01 20:37 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("method: Post. Model: Film. FilmName");
А в чем смысл лога такого? Логгируйте еще что то уникальное, например, наименование или ид фильма

2023-11-01 20:37 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getName() == null || user.getName().trim().isEmpty()) {
Такие проверки можно обьединить, используя для этого StringUtils.isBlank/isNotBlank из библиотеки apache Common 3

Кроме того, использование trim бесполезно

2023-11-01 20:37 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController controller;
Приватный модификатор

2023-11-01 20:37 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    UserController controller;
Модификатор

2023-11-01 20:37 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else if (user.getBirthday().isAfter(LocalDate.now())) {
Проверяйте еще дату на null, иначе можете NPE получить)

2023-11-02 13:35 UTC, ArigatoSlayer commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean isValidFilm(Film film) {
На вебинаре, сказали, что ничего страшного, просто, я не смог для фильмов создать анатацию по типу выпущен позже N-года, но не в будущем

2023-11-03 14:59 UTC, Frilock approved these changes
Принято

2023-11-13 00:57 UTC, merged