добавления в друзья лайки и т.д
ArigatoSlayer/java-filmorate pull request #5
Opened 2023-11-17 15:47 UTC by ArigatoSlayer

2023-11-17 21:33 UTC, Frilock requested changes
Добрый вечер, комментарии в коде

2023-11-17 21:33 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
Нужно поправить сборку, чтобы проходили тесты на гитхаб

2023-11-17 21:33 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;
лучше сразу инициализировать коллекцию, чтобы потом не проверять ее на notNull

2023-11-17 21:33 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Slf4j
Лишняя аннотация

2023-11-17 21:33 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user2 = getUserById(friendId);
Лучше не использовать числовые суффиксы и префисы - используйте слова, friend, например

2023-11-17 21:33 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public boolean isValidFilm(Film film) {
Почему метод публичный? Да и зачем он, если вы валидируете данные при входе, спомощью аннотаций

2023-11-17 21:33 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +//class FilmControllerTest {
Нужно раскоментировать код

2023-11-17 22:56 UTC, ArigatoSlayer commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public boolean isValidFilm(Film film) {
Там еще проходит проверка на дату

2023-11-19 09:45 UTC, Frilock requested changes
Доброе утро, оставил еще ряд комментариев

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return Map.of("С таким индексом значение не найдено", e.getMessage());
Можно лучше:
Можно еще добавить в начале - Ошибка.

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exeptions/NotFoundException.java
> +    public NotFoundException(String e) {
Можно лучше:
Поскольку вы строку передаете, то лучше не e, а message

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return getFilmById(filmId);
Надо исправить:
В каком случае мы попадем в этот return? у вас if - else конструкция

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .limit(count).collect(Collectors.toList());
Можно лучше:
лучше 
.limit
.collect

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Slf4j
Надо исправить:
аннотация для логгирования не убрана

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (getUserById(userId).getFriends().contains(friendId)) {
Можно лучше:
Лучше инвертировать условие, внутри блока if бросать исключение, а остальной код писать уже без вложенности

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } else {
Нужно исправить:
Блок else не нужен, поскольку внутри if у вас идет return, нужно убрать лишнюю вложенность

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            for (Integer id : getUserById(userId).getFriends()) {
Нужно исправить:
getUserById(userId).getFriends() повторяется несколько раз - получите значение в переменную и используйте ее дальше

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public boolean isValidFilm(Film film) {
А почему метод публичный? Он же не используется извне

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        } else if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Можно лучше:
Данная дата является "магической" лучше ее вынести в константу класса, как и число 200 для описания

2023-11-19 09:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    User createUser(@Valid @RequestBody User user);
Нужно исправить:
Данная аннотация @RequestBody тут не нужно

2023-11-20 18:29 UTC, Frilock approved these changes
Принято

2023-11-21 02:42 UTC, merged