databese added
ArigatoSlayer/java-filmorate pull request #6
Opened 2023-12-16 03:02 UTC by ArigatoSlayer

2023-12-17 11:32 UTC, Frilock requested changes
Добрый день,  в целом все понравилось, здорово что сделали отдельный слой мапперов, написал ряд небольших комментариев.

2023-12-17 11:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return service.topFilms(count);
Лучше метод назвать тоже getTopFilms

2023-12-17 11:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    List<Genre> genres;
Модификаторы??

2023-12-17 11:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    int id;
Модификаторы

2023-12-17 11:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    int id;
Модификаторы

2023-12-17 11:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (isValidFilm(film)) {
на мой взгляд, лучше условие сделать так
if (!isValid..) {
throw
}
return ...
Это позволит убрать лишнюю вложенность, у вас такой код присутствует в нескольких местах

2023-12-17 11:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/UserMapper.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
А это зачем?

2023-12-17 11:32 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> -class FilmControllerTest {
А почему тесты удаляете? По идее вам надо их просто немного доработать

2023-12-17 12:33 UTC, ArigatoSlayer commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/UserMapper.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Я читал в ломбоке, это аннотация добавляет для всех переменных значение private final, но мне не очень понравилось, а удалить забыл, а на остальных подбавлять забыл, как то так, да и мне как то ломбок не сильно нравится( но будто бы надо юзать

2023-12-17 12:34 UTC, ArigatoSlayer commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> -class FilmControllerTest {
А ой, я просто когда запускал, из-за того что тесты не работали, надо было что то придумывать, ну и я решил удалить, сейчас исправлю

2023-12-18 20:26 UTC, Frilock approved these changes
Принято, но тест написали довольно странный, но не критично

2023-12-18 20:26 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private Film film1, film2, film3, film4, film5, film1Updated;
в 1 строчку в java не пишут, да и зачем вам столько зависей? 1 проверили и ладно, а то смысл такого кода

2023-12-25 20:04 UTC, merged